/**
 * Batch Q — provider-neutral refund reservation and settlement
  * finalisation. Static source-inspection guard.
   *
    * This migration's runtime behaviour (does approval actually reserve
     * rather than deduct? is the reservation actually consumed exactly once
      * at settlement? etc.) requires a live Postgres instance to prove and is
       * NOT exercised here — see supabase/tests/refund_provider_settlement_proof.sql
        * and supabase/tests/batch_f2_atomic_refund_proof.sql for the live-DB
         * proofs (run via `supabase test db` / CI, not by this Vitest suite).
          * This file pins the SQL source so the intended contract cannot silently
           * regress, mirroring the existing pattern used throughout this repo
            * (e.g. src/tests/admin-refund-wiring.test.ts,
             * supabase/functions/_shared/governance-atomicity-batch1_test.ts).
              *
               * No real provider (Paystack/PayFast) is called anywhere in this file.
                */
                import { describe, it, expect } from "vitest";
                import { readFileSync } from "node:fs";
                import { resolve } from "node:path";

                const MIGRATION_PATH = resolve(
                  __dirname,
                    "../../supabase/migrations/20260707140000_batch_q_refund_reservation_settlement.sql",
                    );
                    const SQL = readFileSync(MIGRATION_PATH, "utf8");

                    describe("Batch Q migration — reservation mechanism", () => {
                      it("adds reserved_refund_tokens to token_balances, non-negative", () => {
                          expect(SQL).toMatch(/ADD COLUMN IF NOT EXISTS reserved_refund_tokens integer NOT NULL DEFAULT 0/);
                              expect(SQL).toMatch(/CHECK \(reserved_refund_tokens >= 0\)/);
                                });

                                  it("creates token_refund_reservations with active/consumed/released status and a unique index per refund_request_id", () => {
                                      expect(SQL).toMatch(/CREATE TABLE IF NOT EXISTS public\.token_refund_reservations/);
                                          expect(SQL).toMatch(/CHECK \(status IN \('active','consumed','released'\)\)/);
                                              expect(SQL).toMatch(
                                                    /CREATE UNIQUE INDEX IF NOT EXISTS idx_token_refund_reservations_refund_request\s*\n\s*ON public\.token_refund_reservations \(refund_request_id\)/,
                                                        );
                                                          });

                                                            it("token_refund_reservations is locked down: RLS enabled, service_role only", () => {
                                                                expect(SQL).toMatch(/ALTER TABLE public\.token_refund_reservations ENABLE ROW LEVEL SECURITY/);
                                                                    expect(SQL).toMatch(/REVOKE ALL ON public\.token_refund_reservations FROM PUBLIC, anon, authenticated/);
                                                                        expect(SQL).toMatch(/GRANT ALL ON public\.token_refund_reservations TO service_role/);
                                                                          });

                                                                            it("adds reservation_id and final_ledger_id linkage columns to refund_requests", () => {
                                                                                expect(SQL).toMatch(/ADD COLUMN IF NOT EXISTS reservation_id uuid REFERENCES public\.token_refund_reservations\(id\)/);
                                                                                    expect(SQL).toMatch(/ADD COLUMN IF NOT EXISTS final_ledger_id uuid/);
                                                                                      });
                                                                                      });

                                                                                      describe("Batch Q migration — approve_refund reserves, does not finally deduct", () => {
                                                                                        it("no longer decrements token_balances.balance directly", () => {
                                                                                            const fnStart = SQL.indexOf("CREATE OR REPLACE FUNCTION public.approve_refund(");
                                                                                                const fnEnd = SQL.indexOf("-- 5. atomic_token_burn");
                                                                                                    const body = SQL.slice(fnStart, fnEnd);
                                                                                                        expect(fnStart).toBeGreaterThan(-1);
                                                                                                            // The old behaviour set balance = GREATEST(0, balance - credits_at_request).
                                                                                                                // Batch Q must not perform that assignment inside approve_refund.
                                                                                                                    expect(body).not.toMatch(/SET\s+balance\s*=\s*GREATEST\(0,\s*balance\s*-/);
                                                                                                                        // Instead it increments the reservation counter.
                                                                                                                            expect(body).toMatch(/SET reserved_refund_tokens = reserved_refund_tokens \+ v_reserve_amount/);
                                                                                                                              });
                                                                                                                              
                                                                                                                                it("computes the reserve amount as GREATEST(0, LEAST(credits_at_request, available))", () => {
                                                                                                                                    expect(SQL).toMatch(
                                                                                                                                          /v_reserve_amount := GREATEST\(0, LEAST\(v_rr\.credits_at_request, v_available\)\)/,
                                                                                                                                              );
                                                                                                                                                });
                                                                                                                                                
                                                                                                                                                  it("is idempotent: replays an already-approved-with-reservation row without re-reserving", () => {
                                                                                                                                                      expect(SQL).toMatch(
                                                                                                                                                            /IF v_rr\.status = 'approved' AND v_rr\.reservation_id IS NOT NULL THEN/,
                                                                                                                                                                );
                                                                                                                                                                    expect(SQL).toMatch(/'deduplicated', true/);
                                                                                                                                                                      });
                                                                                                                                                                      
                                                                                                                                                                        it("guards against a concurrent duplicate-approval race via ON CONFLICT on the reservation table", () => {
                                                                                                                                                                            expect(SQL).toMatch(/ON CONFLICT \(refund_request_id\) DO NOTHING/);
                                                                                                                                                                              });
                                                                                                                                                                              
                                                                                                                                                                                it("tolerates a missing token_balances row rather than hard-failing (matches pre-Batch-Q behaviour)", () => {
                                                                                                                                                                                    // Regression guard for a bug caught during self-review: an early draft
                                                                                                                                                                                        // returned a new TOKEN_BALANCE_NOT_FOUND error when no token_balances
                                                                                                                                                                                            // row existed, which the live F2 atomic-refund proof (which seeds a
                                                                                                                                                                                                // refund with credits_at_request=0 and no token_balances row) would
                                                                                                                                                                                                    // have failed on.
                                                                                                                                                                                                        expect(SQL).not.toMatch(/TOKEN_BALANCE_NOT_FOUND/);
                                                                                                                                                                                                            expect(SQL).toMatch(/v_cur_balance := COALESCE\(v_cur_balance, 0\)/);
                                                                                                                                                                                                                expect(SQL).toMatch(/v_cur_reserved := COALESCE\(v_cur_reserved, 0\)/);
                                                                                                                                                                                                                  });
                                                                                                                                                                                                                  
                                                                                                                                                                                                                    it("records a zero-value refund_hold audit marker in token_ledger, never a real deduction", () => {
                                                                                                                                                                                                                        expect(SQL).toMatch(/'refund_hold', 0, 'allowed'/);
                                                                                                                                                                                                                            expect(SQL).toMatch(/'note', 'Hold only\. No final deduction\./);
                                                                                                                                                                                                                              });
                                                                                                                                                                                                                              
                                                                                                                                                                                                                                it("still sets provider_settlement_status='not_submitted' on approval (unchanged from pre-Batch-Q)", () => {
                                                                                                                                                                                                                                    expect(SQL).toMatch(/provider_settlement_status = 'not_submitted'/);
                                                                                                                                                                                                                                      });
                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                        it("widens token_ledger_action_type_check to allow the new refund_hold marker additively", () => {
                                                                                                                                                                                                                                            // Must not silently drop any of the pre-existing allowed values.
                                                                                                                                                                                                                                                for (const existing of [
                                                                                                                                                                                                                                                      "api_call", "system_adjustment", "declare_intent", "credit",
                                                                                                                                                                                                                                                            "counterparty_sighting", "transaction_complete", "buyer_commit",
                                                                                                                                                                                                                                                                  "credit_purchase", "poi_generation", "refund", "administrative_adjustment",
                                                                                                                                                                                                                                                                        "legacy_pre_production_poi_generation",
                                                                                                                                                                                                                                                                            ]) {
                                                                                                                                                                                                                                                                                  expect(SQL).toMatch(new RegExp(`'${existing}'`));
                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                          expect(SQL).toMatch(/'refund_hold'/);
                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                            describe("Batch Q migration — atomic_token_burn excludes reserved credits from spendable balance", () => {
                                                                                                                                                                                                                                                                                              it("gates the burn UPDATE on (balance - reserved_refund_tokens) >= amount", () => {
                                                                                                                                                                                                                                                                                                  expect(SQL).toMatch(
                                                                                                                                                                                                                                                                                                        /WHERE org_id = p_org_id AND \(balance - COALESCE\(reserved_refund_tokens,\s*0\)\) >= p_amount/,
                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                it("preserves the billing_hold gate and governance emission signature verbatim", () => {
                                                                                                                                                                                                                                                                                                                    expect(SQL).toMatch(/BILLING_HOLD_ACTIVE/);
                                                                                                                                                                                                                                                                                                                        expect(SQL).toMatch(/p_governance jsonb DEFAULT NULL/);
                                                                                                                                                                                                                                                                                                                            expect(SQL).toMatch(
                                                                                                                                                                                                                                                                                                                                  /GRANT EXECUTE ON FUNCTION public\.atomic_token_burn\(uuid, integer, text, text, jsonb\) TO service_role/,
                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                        describe("Batch Q migration — mark_refund_provider_settled consumes reservation, deducts exactly once", () => {
                                                                                                                                                                                                                                                                                                                                          it("consumes the reservation and performs the final deduction on success", () => {
                                                                                                                                                                                                                                                                                                                                              expect(SQL).toMatch(/status = 'consumed', consumed_at = now\(\), final_ledger_id = v_final_ledger_id/);
                                                                                                                                                                                                                                                                                                                                                  expect(SQL).toMatch(
                                                                                                                                                                                                                                                                                                                                                        /SET balance = GREATEST\(0, balance - v_reservation\.reserved_credits\),\s*\n\s*reserved_refund_tokens = GREATEST\(0, reserved_refund_tokens - v_reservation\.reserved_credits\)/,
                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                it("writes the final ledger row with action_type='refund' (not 'refund_hold')", () => {
                                                                                                                                                                                                                                                                                                                                                                    const fnStart = SQL.indexOf("CREATE OR REPLACE FUNCTION public.mark_refund_provider_settled(");
                                                                                                                                                                                                                                                                                                                                                                        const fnEnd = SQL.indexOf("REVOKE ALL ON FUNCTION public.mark_refund_provider_settled");
                                                                                                                                                                                                                                                                                                                                                                            const body = SQL.slice(fnStart, fnEnd);
                                                                                                                                                                                                                                                                                                                                                                                expect(body).toMatch(/v_rr\.org_id, 'refund', v_reservation\.reserved_credits, 'allowed'/);
                                                                                                                                                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                    it("preserves idempotency on same provider_refund_reference and conflict-detection on a different one", () => {
                                                                                                                                                                                                                                                                                                                                                                                        expect(SQL).toMatch(/'success', true, 'deduplicated', true/);
                                                                                                                                                                                                                                                                                                                                                                                            expect(SQL).toMatch(/REFUND_SETTLEMENT_CONFLICT/);
                                                                                                                                                                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                it("never double-deducts on a second call once the reservation is already consumed", () => {
                                                                                                                                                                                                                                                                                                                                                                                                    expect(SQL).toMatch(/IF v_reservation\.status = 'consumed' THEN/);
                                                                                                                                                                                                                                                                                                                                                                                                      });
                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                        it("has a legacy-row fallback for refunds approved before this migration (no reservation to consume)", () => {
                                                                                                                                                                                                                                                                                                                                                                                                            expect(SQL).toMatch(/IF v_rr\.reservation_id IS NULL THEN/);
                                                                                                                                                                                                                                                                                                                                                                                                                expect(SQL).toMatch(/legacy_pre_reservation/);
                                                                                                                                                                                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                    it("opens a refund_settlement_mismatch risk item on currency mismatch and does not move money", () => {
                                                                                                                                                                                                                                                                                                                                                                                                                        expect(SQL).toMatch(/refund_settlement_mismatch/);
                                                                                                                                                                                                                                                                                                                                                                                                                            expect(SQL).toMatch(/REFUND_SETTLEMENT_MISMATCH/);
                                                                                                                                                                                                                                                                                                                                                                                                                                // The mismatch branch must RETURN before reaching the deduction UPDATE.
                                                                                                                                                                                                                                                                                                                                                                                                                                    const mismatchIdx = SQL.indexOf("REFUND_SETTLEMENT_MISMATCH");
                                                                                                                                                                                                                                                                                                                                                                                                                                        const deductIdx = SQL.indexOf("Consume the reservation and finally deduct");
                                                                                                                                                                                                                                                                                                                                                                                                                                            expect(mismatchIdx).toBeGreaterThan(-1);
                                                                                                                                                                                                                                                                                                                                                                                                                                                expect(deductIdx).toBeGreaterThan(-1);
                                                                                                                                                                                                                                                                                                                                                                                                                                                    expect(mismatchIdx).toBeLessThan(deductIdx);
                                                                                                                                                                                                                                                                                                                                                                                                                                                      });
                                                                                                                                                                                                                                                                                                                                                                                                                                                      });
                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                      describe("Batch Q migration — mark_refund_manually_settled_with_governance consumes reservation, deducts exactly once", () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                        it("preserves the governance/hash-chain/idempotency contract verbatim", () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                            expect(SQL).toMatch(/length\(btrim\(p_notes\)\) < 20/);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                expect(SQL).toMatch(/admin\.hq_decision_recorded/);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    expect(SQL).toMatch(/encode\(digest\(v_canonical, 'sha256'\), 'hex'\)/);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        it("consumes the reservation and finally deducts when one exists", () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const fnStart = SQL.indexOf("CREATE OR REPLACE FUNCTION public.mark_refund_manually_settled_with_governance(");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                expect(fnStart).toBeGreaterThan(-1);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const body = SQL.slice(fnStart);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        expect(body).toMatch(/IF v_rr\.reservation_id IS NOT NULL THEN/);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            expect(body).toMatch(/IF FOUND AND v_reservation\.status = 'active' THEN/);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                expect(body).toMatch(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      /SET balance = GREATEST\(0, balance - v_reservation\.reserved_credits\),\s*\n\s*reserved_refund_tokens = GREATEST\(0, reserved_refund_tokens - v_reservation\.reserved_credits\)/,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              it("skips a second deduction for legacy pre-Batch-Q rows with no reservation", () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  expect(SQL).toMatch(/legacy pre-Batch-Q refund\), credits were/);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    describe("Batch Q migration — surface_unsettled_refunds wording only, logic unchanged", () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      it("no longer claims credits were reversed in-platform; says they are held in reserve", () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          expect(SQL).not.toMatch(/Credits were reversed in-platform/);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              expect(SQL).toMatch(/Credits are held in reserve pending settlement \(Batch Q\)/);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  it("dedup/open/resolve logic on refund_settlement_pending risk items is unchanged", () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      expect(SQL).toMatch(/'refund_settlement_pending:' \|\| r\.id::text/);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          expect(SQL).toMatch(/COALESCE\(rr\.provider_settlement_status, ''\) <> 'not_submitted'/);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            describe("Batch Q migration — PayFast is not given fake automated settlement behaviour", () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              it("does not implement or reference a PayFast refund-status polling/checker function", () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  // This migration must not fabricate a PayFast automated refund-status
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      // API. Confirmed absent from the current codebase in Phase 1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          // inspection (docs/payfast-phase-2j-customer-rollout-report.md §9).
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              expect(SQL).not.toMatch(/payfast[_-]?refund[_-]?status/i);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  expect(SQL).not.toMatch(/PAYFAST_REFUND_STATUS_CHECK/i);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      it("mark_refund_provider_settled remains provider-neutral (no provider name branching)", () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const fnStart = SQL.indexOf("CREATE OR REPLACE FUNCTION public.mark_refund_provider_settled(");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const fnEnd = SQL.indexOf("REVOKE ALL ON FUNCTION public.mark_refund_provider_settled");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const body = SQL.slice(fnStart, fnEnd);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      expect(body.toLowerCase()).not.toMatch(/paystack|payfast/);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        describe("Batch Q — fail-closed PayFast adapter-gap constant (Deno shared policy)", () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const SHARED = readFileSync(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              resolve(__dirname, "../../supabase/functions/_shared/dec-007-policy.ts"),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  "utf8",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      it("defines PAYFAST_REFUND_STATUS_CHECK_NOT_IMPLEMENTED as the required fail-closed code", () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          expect(SHARED).toMatch(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                /PAYFAST_REFUND_STATUS_CHECK_NOT_IMPLEMENTED\s*=\s*"PAYFAST_REFUND_STATUS_CHECK_NOT_IMPLEMENTED"/,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        it("cites the Phase 1 evidence that PayFast has no automated refund-status API in this codebase", () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            expect(SHARED).toMatch(/payfast-phase-2j-customer-rollout-report\.md/);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                it("mirrors the reservation statuses and customer labels from the TS SSOT", () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    expect(SHARED).toMatch(/REFUND_RESERVATION_STATUSES\s*=\s*\[\s*\n\s*"active",\s*\n\s*"consumed",\s*\n\s*"released",/);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        expect(SHARED).toMatch(/CUSTOMER_REFUND_LABELS\s*=\s*\{/);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          describe("Batch Q — no real provider or network calls anywhere in this test file's fixtures", () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            it("this file never calls a live Paystack/PayFast endpoint", () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Meta-guard: the test file itself must not contain outbound HTTP
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // calls to a real provider. It only reads local source files.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const selfSrc = readFileSync(__filename, "utf8");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            expect(selfSrc).not.toMatch(/https?:\/\/.*\.(paystack|payfast)\.co/i);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                expect(selfSrc).not.toMatch(/\bfetch\(/);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  });
