/**
 * Institutional Funder Evidence Workspace — Batch 7 pack-content wiring.
  *
   * IMPORTANT LIMITATION: this environment has no terminal/code-execution
    * tool available, so these are STATIC SOURCE-CONFORMANCE tests (readFileSync
     * + regex/string assertions against the migration and edge function source),
      * consistent with the existing style used across this repo (e.g.
       * src/tests/p5-batch3-stage3-edge-summary-static.test.ts). They were
        * authored to run under vitest but have NOT been executed in this session
         * because no vitest/tsgo runner is available here. They prove the shape of
          * the shipped code, not runtime behaviour. Genuine execution
           * (`npx vitest run` / `npx tsgo --noEmit`) should be run in a
            * terminal-capable environment before treating this batch as verified.
             */
             import { describe, it, expect } from "vitest";
             import { readFileSync, existsSync } from "node:fs";
             import { join } from "node:path";

             const ROOT = process.cwd();
             const MIGRATION = join(ROOT, "supabase/migrations/20260712160000_fw_batch7_pack_content_projection.sql");
             const EDGE_FN = join(ROOT, "supabase/functions/funder-pack-generate/index.ts");

             describe("Batch 7 — fw_admin_funder_pack_content_v1 migration", () => {
               it("exists", () => {
                   expect(existsSync(MIGRATION)).toBe(true);
                     });

                       const sql = existsSync(MIGRATION) ? readFileSync(MIGRATION, "utf8") : "";

                         it("is additive: defines the new function without ALTER/DROP on any existing table, enum or RLS policy", () => {
                             expect(sql).toMatch(/CREATE OR REPLACE FUNCTION public\.fw_admin_funder_pack_content_v1/);
                                 expect(sql).not.toMatch(/ALTER TABLE/i);
                                     expect(sql).not.toMatch(/DROP (TABLE|POLICY|TYPE)/i);
                                       });

                                         it("is platform-admin gated and SECURITY DEFINER", () => {
                                             expect(sql).toMatch(/SECURITY DEFINER/);
                                                 expect(sql).toMatch(/p5b3_is_platform_admin/);
                                                   });

                                                     it("grants EXECUTE only to authenticated/service_role, never PUBLIC or anon", () => {
                                                         expect(sql).toMatch(/REVOKE EXECUTE ON FUNCTION public\.fw_admin_funder_pack_content_v1\(uuid\) FROM PUBLIC, anon;/);
                                                             expect(sql).toMatch(/GRANT EXECUTE ON FUNCTION public\.fw_admin_funder_pack_content_v1\(uuid\) TO authenticated, service_role;/);
                                                               });

                                                                 it("resolves deal_reference only via a UUID-shaped match, never trusts free text directly", () => {
                                                                     expect(sql).toMatch(/\^\[0-9a-f\]\{8\}-\[0-9a-f\]\{4\}-\[0-9a-f\]\{4\}-\[0-9a-f\]\{4\}-\[0-9a-f\]\{12\}\$/);
                                                                         expect(sql).toMatch(/v_match_resolved/);
                                                                           });

                                                                             it("never fabricates buyer/seller/WaD/evidence content when the match does not resolve", () => {
                                                                                 expect(sql).toMatch(/No linked record was available at the time of generation\./);
                                                                                   });

                                                                                     it("keeps buyer and seller sourced from distinct organisation ids (no cross-party swap)", () => {
                                                                                         expect(sql).toMatch(/v_match\.buyer_org_id/);
                                                                                             expect(sql).toMatch(/v_match\.seller_org_id/);
                                                                                                 // buyer_org and seller_org must be selected into separate record variables
                                                                                                     expect(sql).toMatch(/INTO v_buyer_org FROM public\.organizations WHERE id = v_match\.buyer_org_id/);
                                                                                                         expect(sql).toMatch(/INTO v_seller_org FROM public\.organizations WHERE id = v_match\.seller_org_id/);
                                                                                                           });
                                                                                                           
                                                                                                             it("never selects raw/sensitive fields (bank details, identity numbers, provider payloads, raw storage paths)", () => {
                                                                                                                 expect(sql).not.toMatch(/bank_account/i);
                                                                                                                     expect(sql).not.toMatch(/raw_provider_payload/i);
                                                                                                                         expect(sql).not.toMatch(/storage_path/i);
                                                                                                                             expect(sql).not.toMatch(/file_reference/i);
                                                                                                                                 expect(sql).not.toMatch(/id_number|passport|ssn/i);
                                                                                                                                   });
                                                                                                                                   
                                                                                                                                     it("bank-confidence always returns an explicit not_applicable status and is never computed from another field", () => {
                                                                                                                                         expect(sql).toMatch(/'bank_confidence',\s*jsonb_build_object\(\s*'available', false,\s*'status', 'not_applicable'/);
                                                                                                                                           });
                                                                                                                                           
                                                                                                                                             it("finality snapshot is explicitly left unresolved (no p5_batch4 join is asserted as reliable)", () => {
                                                                                                                                                 expect(sql).toMatch(/'finality_snapshot',\s*jsonb_build_object\(\s*'available', false/);
                                                                                                                                                     expect(sql).toMatch(/product decision is required/);
                                                                                                                                                       });
                                                                                                                                                       
                                                                                                                                                         it("missing_evidence never claims a required/missing distinction that isn't backed by a checklist source", () => {
                                                                                                                                                             expect(sql).toMatch(/No canonical required-evidence checklist exists at the match level/);
                                                                                                                                                               });
                                                                                                                                                               
                                                                                                                                                                 it("reuses the existing safe exception RPC rather than querying a raw exceptions table directly", () => {
                                                                                                                                                                     expect(sql).toMatch(/p5b6_list_exceptions_safe/);
                                                                                                                                                                         expect(sql).not.toMatch(/FROM public\.p5_batch6_exceptions/i);
                                                                                                                                                                           });
                                                                                                                                                                           
                                                                                                                                                                             it("labels the risk/exception summary as organisation-scoped, not deal-scoped", () => {
                                                                                                                                                                                 expect(sql).toMatch(/'risk_exception_scope', 'organisation'/);
                                                                                                                                                                                   });
                                                                                                                                                                                   
                                                                                                                                                                                     it("gracefully degrades (does not raise) if the exception RPC call fails", () => {
                                                                                                                                                                                         expect(sql).toMatch(/EXCEPTION WHEN OTHERS THEN\s*\n\s*v_risk_exceptions := NULL;/);
                                                                                                                                                                                           });
                                                                                                                                                                                           });
                                                                                                                                                                                           
                                                                                                                                                                                           describe("Batch 7 — funder-pack-generate wiring", () => {
                                                                                                                                                                                             const src = existsSync(EDGE_FN) ? readFileSync(EDGE_FN, "utf8") : "";
                                                                                                                                                                                             
                                                                                                                                                                                               it("edge function exists", () => {
                                                                                                                                                                                                   expect(existsSync(EDGE_FN)).toBe(true);
                                                                                                                                                                                                     });
                                                                                                                                                                                                     
                                                                                                                                                                                                       it("calls the new canonical content projection RPC", () => {
                                                                                                                                                                                                           expect(src).toMatch(/fw_admin_funder_pack_content_v1/);
                                                                                                                                                                                                             });
                                                                                                                                                                                                             
                                                                                                                                                                                                               it("still calls the existing Batch 4 context RPC and seal RPC unchanged (regression)", () => {
                                                                                                                                                                                                                   expect(src).toMatch(/fw_admin_pack_generation_context_v1/);
                                                                                                                                                                                                                       expect(src).toMatch(/fw_admin_seal_pack_v1/);
                                                                                                                                                                                                                         });
                                                                                                                                                                                                                         
                                                                                                                                                                                                                           it("does not hard-fail generation if the content projection call errors (existing releases keep working)", () => {
                                                                                                                                                                                                                               const contentBlockMatch = src.match(/let content: PackContent \| null = null;[\s\S]*?content = null;\s*\n\s*}/);
                                                                                                                                                                                                                                   expect(contentBlockMatch).not.toBeNull();
                                                                                                                                                                                                                                       expect(contentBlockMatch?.[0]).toMatch(/try \{/);
                                                                                                                                                                                                                                           expect(contentBlockMatch?.[0]).toMatch(/catch \(_e\) \{/);
                                                                                                                                                                                                                                             });
                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                               it("no longer renders the generic placeholder for the nine previously-unconnected sections", () => {
                                                                                                                                                                                                                                                   // The static SECTIONS array with "Not connected in this version." for
                                                                                                                                                                                                                                                       // buyer/seller/verification/IDV-KYB/WaD/bank-confidence/missing-evidence/
                                                                                                                                                                                                                                                           // risk-exception/finality must be gone; those sections are now built by
                                                                                                                                                                                                                                                               // buildSections()/buildPartySummaryLines()/etc. from real content.
                                                                                                                                                                                                                                                                   expect(src).not.toMatch(/const SECTIONS: Array<\{ title: string; body: string\[\] \}> = \[/);
                                                                                                                                                                                                                                                                       expect(src).toMatch(/function buildSections\(/);
                                                                                                                                                                                                                                                                         });
                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                           it("keeps an honest fallback phrase (not the old generic placeholder) for genuinely unresolved sections", () => {
                                                                                                                                                                                                                                                                               expect(src).toMatch(/No linked record was available at the time of generation\./);
                                                                                                                                                                                                                                                                                   expect(src).toMatch(/Not applicable\./);
                                                                                                                                                                                                                                                                                     });
                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                       it("buyer and seller section builders are called with distinct content fields (no cross-party swap)", () => {
                                                                                                                                                                                                                                                                                           expect(src).toMatch(/buildPartySummaryLines\(c\.buyer_summary\)/);
                                                                                                                                                                                                                                                                                               expect(src).toMatch(/buildPartySummaryLines\(c\.seller_summary\)/);
                                                                                                                                                                                                                                                                                                 });
                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                   it("evidence register still states raw documents are excluded by default (regression)", () => {
                                                                                                                                                                                                                                                                                                       expect(src).toMatch(/Raw documents are excluded from this V1 pack by default\./);
                                                                                                                                                                                                                                                                                                         });
                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                           it("disclaimer explicitly states the hash verifies the file only, not every underlying declaration", () => {
                                                                                                                                                                                                                                                                                                               expect(src).toMatch(/verifies the integrity of this generated file only/);
                                                                                                                                                                                                                                                                                                                 });
                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                   it("surfaces deal_reference_resolved in the response without hard-blocking generation on an unresolved reference", () => {
                                                                                                                                                                                                                                                                                                                       expect(src).toMatch(/deal_reference_resolved: content\?\.deal_reference_resolved \?\? false/);
                                                                                                                                                                                                                                                                                                                           // No early-return/hard-reject branch keyed on an unresolved reference.
                                                                                                                                                                                                                                                                                                                               expect(src).not.toMatch(/deal_reference_resolved.*return json\(\{ error:/s);
                                                                                                                                                                                                                                                                                                                                 });
                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                   it("SHA-256 is still computed from the final PDF bytes after content is embedded (regression)", () => {
                                                                                                                                                                                                                                                                                                                                       const buildOrder = src.indexOf("buildPdf(ctx, packId, generatedByEmail, generatedAt, content)");
                                                                                                                                                                                                                                                                                                                                           const hashOrder = src.indexOf("sha256Hex(pdfBytes)");
                                                                                                                                                                                                                                                                                                                                               expect(buildOrder).toBeGreaterThan(-1);
                                                                                                                                                                                                                                                                                                                                                   expect(hashOrder).toBeGreaterThan(-1);
                                                                                                                                                                                                                                                                                                                                                       expect(buildOrder).toBeLessThan(hashOrder);
                                                                                                                                                                                                                                                                                                                                                         });
                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                           it("watermark/footer drawing is unchanged (regression)", () => {
                                                                                                                                                                                                                                                                                                                                                               expect(src).toMatch(/drawWatermark/);
                                                                                                                                                                                                                                                                                                                                                                   expect(src).toMatch(/IZENZO · CONFIDENTIAL/);
                                                                                                                                                                                                                                                                                                                                                                     });
                                                                                                                                                                                                                                                                                                                                                                     });
                                                                                                                                                                                                                                                                                                                                                                     
