/**
 * P-5 Batch 5 — Phase 5
 * API-safe preview panel.
 *
 * Strictly uses `projectFinalityToApiSafe` from Phase 4. Does NOT hand-roll
 * projection. Only shown to users with `can_view_api_safe_preview`.
 */
import { useMemo, useState } from "react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Checkbox } from "@/components/ui/checkbox";
import {
  P5B5_API_SAFE_FIELDS,
  projectFinalityToApiSafe,
  type P5B5ProjectionInput,
} from "@/lib/p5-batch5/api-safe";
import { P5B5_API_SCOPES, type P5B5ApiScope, type P5B5Role, getP5B5Capabilities, type P5B5PermissionContext } from "@/lib/p5-batch5/permissions";

export interface P5B5ApiSafePreviewPanelProps {
  role: P5B5Role;
  context?: P5B5PermissionContext;
  input: P5B5ProjectionInput | null;
}

const HIDDEN_FIELD_HINTS: Record<string, string> = {
  evidence_rating: "Requires evidence_rating.read scope.",
  finality_record_reference: "Requires audit.read scope.",
  hash_reference: "Requires audit.read scope.",
  provider_dependency_status: "Requires provider_dependency.read or audit.read scope.",
};

export function P5B5ApiSafePreviewPanel({ role, context, input }: P5B5ApiSafePreviewPanelProps) {
  const caps = getP5B5Capabilities(role, context);
  const [scopes, setScopes] = useState<Set<P5B5ApiScope>>(new Set(["finality.read"]));

  const projection = useMemo(
    () => projectFinalityToApiSafe(input, { api_scopes: Array.from(scopes) }),
    [input, scopes],
  );

  if (!caps.can_view_api_safe_preview) {
    return (
      <Card>
        <CardHeader>
          <CardTitle className="text-base">API-safe preview</CardTitle>
          <CardDescription>You do not have permission to view this panel.</CardDescription>
        </CardHeader>
      </Card>
    );
  }

  const hiddenForScope = !projection.blocked
    ? P5B5_API_SAFE_FIELDS.filter((f) => HIDDEN_FIELD_HINTS[f] && (projection as Record<string, unknown>)[f] == null)
    : [];

  return (
    <Card data-p5b5-api-safe-preview>
      <CardHeader>
        <CardTitle className="text-base">API-safe preview</CardTitle>
        <CardDescription>
          What an API client with the selected scopes would receive. Generated by the
          Phase 4 projection helper.
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="flex flex-wrap gap-3">
          {P5B5_API_SCOPES.map((s) => (
            <Label key={s} className="flex items-center gap-2 text-xs">
              <Checkbox
                checked={scopes.has(s)}
                onCheckedChange={(c) => {
                  const next = new Set(scopes);
                  if (c === true) next.add(s); else next.delete(s);
                  // finality.read always required
                  next.add("finality.read");
                  setScopes(next);
                }}
              />
              {s}
            </Label>
          ))}
        </div>

        {projection.blocked ? (
          <div className="rounded-md border border-dashed p-3 text-sm">
            <div className="font-medium">Blocked: {projection.reason}</div>
            <div className="text-muted-foreground">{projection.message}</div>
            <div className="mt-2 text-xs text-muted-foreground">
              schema {projection.schema_version} / outcome {projection.outcome_code_version}
            </div>
          </div>
        ) : (
          <pre className="overflow-x-auto rounded-md bg-muted p-3 text-xs">
            {JSON.stringify(projection, null, 2)}
          </pre>
        )}

        {hiddenForScope.length > 0 && (
          <div className="text-xs text-muted-foreground">
            Hidden in this scope:
            <ul className="ml-4 list-disc">
              {hiddenForScope.map((f) => (
                <li key={f}>
                  <code>{f}</code> — {HIDDEN_FIELD_HINTS[f]}
                </li>
              ))}
            </ul>
          </div>
        )}
      </CardContent>
    </Card>
  );
}

export default P5B5ApiSafePreviewPanel;
