/**
 * P-5 Batch 7 — Phase 3: API v1 read-only projection layer (client helpers).
 *
 * All callers MUST use these helpers when reading data for the Batch 7 v1 API
 * surface. Helpers:
 *   - call the Phase 3 SECURITY DEFINER RPCs (no direct table reads),
 *   - strip every field that is NOT in P5_BATCH7_API_V1_VISIBLE_FIELDS,
 *   - hard-fail (throw) if any P5_BATCH7_FORBIDDEN_EXTERNAL_FIELDS slip through.
 *
 * Read-only. No write/mutation helpers live here.
 */
import { supabase } from "@/integrations/supabase/client";
import {
  P5_BATCH7_API_V1_VISIBLE_FIELDS,
  P5_BATCH7_FORBIDDEN_EXTERNAL_FIELDS,
  type P5Batch7ApiV1Field,
} from "./registry";

const ALLOW = new Set<string>(P5_BATCH7_API_V1_VISIBLE_FIELDS as readonly string[]);
const FORBIDDEN = new Set<string>(
  P5_BATCH7_FORBIDDEN_EXTERNAL_FIELDS as readonly string[],
);

export type P5Batch7ApiV1Row = Partial<Record<P5Batch7ApiV1Field, unknown>>;

export interface P5Batch7ApiV1Envelope<T> {
  readonly data: ReadonlyArray<T>;
  readonly page: number;
  readonly page_size: number;
  readonly total_count: number | null;
  readonly next_cursor: string | null;
  readonly as_of: string | null;
  readonly is_stale: boolean;
  readonly api_version: "v1";
  readonly error: null | { code: string; message: string };
}

/** Strip a raw row to the Phase 1 allow-list. Throws on forbidden fields. */
export function projectToApiV1<T extends Record<string, unknown>>(
  raw: T,
  context = "p5b7_api_v1",
): P5Batch7ApiV1Row {
  const out: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(raw)) {
    if (FORBIDDEN.has(k)) {
      throw new Error(
        `[${context}] forbidden field "${k}" attempted to leak into API v1 output`,
      );
    }
    if (ALLOW.has(k)) out[k] = v;
  }
  return out as P5Batch7ApiV1Row;
}

/** Project + assert for an array of rows. */
export function projectRowsToApiV1<T extends Record<string, unknown>>(
  rows: ReadonlyArray<T>,
  context = "p5b7_api_v1",
): ReadonlyArray<P5Batch7ApiV1Row> {
  return rows.map((r) => projectToApiV1(r, context));
}

/** Build an envelope, computing `as_of` / `is_stale` from the most-recent row. */
export function buildApiV1Envelope<T extends P5Batch7ApiV1Row>(
  rows: ReadonlyArray<T>,
  opts: {
    page?: number;
    page_size?: number;
    total_count?: number | null;
    next_cursor?: string | null;
    error?: { code: string; message: string } | null;
  } = {},
): P5Batch7ApiV1Envelope<T> {
  let mostRecent: string | null = null;
  let anyStale = false;
  for (const r of rows) {
    const asOf = r.as_of as string | undefined;
    if (typeof asOf === "string") {
      if (!mostRecent || asOf > mostRecent) mostRecent = asOf;
    }
    if (r.is_stale === true) anyStale = true;
  }
  return {
    data: rows,
    page: opts.page ?? 1,
    page_size: opts.page_size ?? rows.length,
    total_count: opts.total_count ?? null,
    next_cursor: opts.next_cursor ?? null,
    as_of: mostRecent,
    is_stale: anyStale,
    api_version: "v1",
    error: opts.error ?? null,
  };
}

/** List cases via the Phase 3 RPC, scoped server-side. */
export async function p5b7ApiV1ListCases(params: {
  org_id?: string | null;
  funder_org_id?: string | null;
  limit?: number;
  cursor?: string | null;
}): Promise<P5Batch7ApiV1Envelope<P5Batch7ApiV1Row>> {
  // Cast: this RPC is defined in the Phase 3 migration; types are regenerated by the platform.
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const { data, error } = await (supabase as any).rpc("p5b7_api_v1_list_cases", {
    p_org_id: params.org_id ?? null,
    p_funder_org_id: params.funder_org_id ?? null,
    p_limit: params.limit ?? 50,
    p_cursor: params.cursor ?? null,
  });
  if (error) {
    return buildApiV1Envelope([], {
      page_size: params.limit ?? 50,
      error: { code: "p5b7_api_v1_list_cases_failed", message: error.message },
    });
  }
  const safe = projectRowsToApiV1(
    (data ?? []) as ReadonlyArray<Record<string, unknown>>,
    "p5b7_api_v1_list_cases",
  );
  return buildApiV1Envelope(safe, { page_size: params.limit ?? 50 });
}

/** Get one case (scope still enforced by the RPC). */
export async function p5b7ApiV1GetCase(
  caseId: string,
): Promise<P5Batch7ApiV1Envelope<P5Batch7ApiV1Row>> {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const { data, error } = await (supabase as any).rpc("p5b7_api_v1_get_case", {
    p_case_id: caseId,
  });
  if (error) {
    return buildApiV1Envelope([], {
      page_size: 1,
      error: { code: "p5b7_api_v1_get_case_failed", message: error.message },
    });
  }
  const safe = projectRowsToApiV1(
    (data ?? []) as ReadonlyArray<Record<string, unknown>>,
    "p5b7_api_v1_get_case",
  );
  return buildApiV1Envelope(safe, { page_size: 1 });
}
