#!/usr/bin/env node
/**
 * Route Codegen — emits src/lib/routes.generated.ts.
 *
 * Reads every `<Route path="…">` from App.tsx + nested shells (Desk, HQ,
 * DeveloperCenter) using the same extractor that powers `check:routes`,
 * then writes a typed module exposing:
 *
 *   • RoutePath           – string-literal union of every concrete route
 *   • ROUTE_PATHS         – frozen array of those literals (for runtime checks)
 *   • routeTo(path, opts) – typed builder; substitutes :params and ?query
 *   • assertRoutePath(s)  – runtime guard for strings that come from data
 *                           (e.g. notification deep-links, server payloads)
 *
 * Why we generate this instead of hand-maintaining a constants file:
 * the previous `ROUTES` constant in src/lib/constants.ts was 90% stale (still
 * listing /dashboard/* and /admin/* paths that no longer exist) and missing
 * the route the KYB redirect actually needed (/desk/settings/company). A
 * generated artefact cannot drift — it is rebuilt on every build.
 *
 * Wired into npm run build via `prebuild` (see package.json).
 */

import { writeFileSync } from "fs";
import { collectRoutePatterns, loadRouteConstants, walk } from "./lib/collect-routes.mjs";

const OUT = "src/lib/routes.generated.ts";

// ── Collect ────────────────────────────────────────────────────────────────
const files = walk("src");
const routeConsts = loadRouteConstants();
const rawPatterns = [...collectRoutePatterns(files, routeConsts)];

if (rawPatterns.length === 0) {
  console.error("[generate-routes] FATAL: no routes discovered. Refusing to emit empty union.");
  process.exit(2);
}

// ── Filter to surfaces useful for typed `routeTo()` ────────────────────────
// Drop:
//  - the "*" catch-all (NotFound, not a navigable route)
//  - bare shell prefixes (e.g. "/desk") — kept separately as overview entries
//  - shell catch-alls (e.g. "/desk/*") — they're matched implicitly by
//    concrete children; emitting them as a literal type would let callers
//    pass any "/desk/anything" string and bypass type safety.
const SHELL_OVERVIEWS = new Set(["/desk", "/developer", "/hq"]);
const concrete = rawPatterns
  .filter((p) => p !== "*")
  .filter((p) => !p.endsWith("/*"))
  .filter((p) => p.length > 0)
  // Sort: shorter & alphabetic first, gives readable output diff.
  .sort();

// Always include shell overviews (they render an index element even when
// no `<Route path="">` exists for the bare prefix).
for (const s of SHELL_OVERVIEWS) if (!concrete.includes(s)) concrete.push(s);
concrete.sort();

const literals = concrete.map((p) => JSON.stringify(p)).join(" | ");

// ── Emit ───────────────────────────────────────────────────────────────────
const banner = `/* eslint-disable */
// AUTO-GENERATED by scripts/generate-routes.mjs — DO NOT EDIT BY HAND.
// Regenerated on every \`npm run build\` (and \`npm run check:routes\`).
// Source of truth: every <Route path="…"> in src/App.tsx + nested shells.
//
// Why this file exists:
//   • The "/desk/settings/identity" → 404 bug shipped because nothing forced
//     <Link to="…"> targets to be type-checked against real routes.
//   • Hand-maintained ROUTES constants drift; a generated union cannot.
//   • routeTo() is the only sanctioned way to build an in-app URL going
//     forward. ESLint (eventually) bans literal "/desk/…" strings outside
//     this file and route-config files.
`;

const body = `
export const ROUTE_PATHS = [
${concrete.map((p) => `  ${JSON.stringify(p)},`).join("\n")}
] as const;

export type RoutePath = ${literals};

/**
 * Runtime guard for paths sourced from data (notification payloads, server
 * responses, etc.). Returns the path narrowed to RoutePath, or throws.
 */
export function assertRoutePath(path: string): RoutePath {
  if ((ROUTE_PATHS as readonly string[]).includes(path)) {
    return path as RoutePath;
  }
  throw new Error(\`assertRoutePath: "\${path}" is not a registered route. Add it to App.tsx or fix the typo.\`);
}

/**
 * Returns true if \`path\` (with optional ?query) targets a registered
 * route pattern. Used by the route guard's runtime tests.
 */
export function isRoutePath(path: string): path is RoutePath {
  const stripped = path.split("?")[0].split("#")[0];
  return (ROUTE_PATHS as readonly string[]).includes(stripped);
}

/** Options accepted by routeTo(). */
export interface RouteToOptions {
  /** Substitute :param segments. e.g. { matchId: "abc" } turns
   *  "/desk/match/:matchId" into "/desk/match/abc". */
  params?: Record<string, string | number>;
  /** Append a querystring. Values are coerced to strings; undefined is skipped. */
  query?: Record<string, string | number | boolean | undefined | null>;
}

/**
 * Type-safe URL builder.
 *
 * Examples:
 *   routeTo("/desk/settings/company")
 *   routeTo("/desk/settings/company", { query: { step: "entity" } })
 *   routeTo("/desk/match/:matchId", { params: { matchId } })
 *
 * A typo like routeTo("/desk/settings/identity") fails to compile because
 * the literal isn't in the RoutePath union.
 */
export function routeTo(path: RoutePath, opts: RouteToOptions = {}): string {
  let out: string = path;
  if (opts.params) {
    for (const [k, v] of Object.entries(opts.params)) {
      out = out.replace(\`:\${k}\`, encodeURIComponent(String(v)));
    }
  }
  if (opts.query) {
    const usp = new URLSearchParams();
    for (const [k, v] of Object.entries(opts.query)) {
      if (v === undefined || v === null || v === "") continue;
      usp.set(k, String(v));
    }
    const qs = usp.toString();
    if (qs) out += \`?\${qs}\`;
  }
  return out;
}
`;

writeFileSync(OUT, banner + body);
console.log(`✅ generate-routes — wrote ${concrete.length} routes to ${OUT}`);
