-- Institutional Funder Evidence Workspace -- Batch 7
-- Canonical, server-side, funder-safe pack-content projection.
-- Additive only. Does not modify any Batch 1-6 table, enum, RPC signature
-- or RLS policy. This function is read-only (SELECT-only against existing
-- tables/RPCs) and writes no data itself.
--
-- Full evidence-backed source-mapping matrix, confidence decisions and
-- unresolved-section rationale: docs/funder-workspace-batch7-pack-content-report.md
--
-- Summary of source decisions:
--   * deal_reference resolution: funder_deal_releases.deal_reference is free
--     text with no FK anywhere in the schema (confirmed: NewRelease.tsx is a
--     plain text input with no lookup/validation). This function attempts to
--     resolve it as a matches.id UUID. When it resolves, buyer/seller/WaD/
--     evidence-register content is sourced from that match. When it does not
--     resolve, those sections are returned as explicitly unavailable -- never
--     fabricated, never inferred.
--   * Buyer/seller summary: matches.buyer_org_id/seller_org_id -> organizations
--     (legal_name, trading_name, registration_number, jurisdictions).
--   * Verification / IDV-KYB: p5scr_subjects (organisation_id, party_role IN
--     ('buyer_company','seller_company')) joined to p5scr_check_state
--     (category, state) for the resolved buyer/seller organisation ids.
--   * WaD status: wads (poi_id = matches.id) -- the same relationship already
--     used by supabase/functions/deal-certificate/index.ts.
--   * Evidence register: match_documents (match_id = matches.id). Safe
--     metadata only (doc_type, filename, status, hash presence, date). No
--     raw file bytes, no storage paths, no unrestricted URLs are returned.
--   * Missing evidence: only the "received" side is derivable from
--     match_documents. No canonical required-evidence checklist exists at
--     the match level anywhere in this codebase, so "required and missing"
--     is intentionally NOT computed -- this is reported as unresolved.
--   * Risk / exception summary: reuses the existing safe RPC
--     p5b6_list_exceptions_safe (already used by the P-5 Batch 6 admin
--     workbench), filtered in this function to the resolved buyer/seller
--     organisation ids. This is ORGANISATION-scoped, not deal-scoped -- no
--     deal-scoped exception source exists in the platform -- so it is
--     explicitly labelled as an organisation-level view, not a deal-level one.
--   * Bank-confidence: NO authoritative source exists anywhere in the
--     platform (a repository-wide search for any bank-confidence / bank
--     verification record returned zero results; the only related hit,
--     `bank_account_holder_mismatch`, is a document-review rejection reason,
--     not a verification record). This section is intentionally left
--     unresolved and always returns an explicit not_applicable status.
--   * Finality snapshot: NO reliable join exists from deal_reference/matches
--     to p5_batch4_execution_cases. `linked_transaction_id` on that table has
--     no FK constraint and is never populated from matches/deal_reference in
--     any code path found in this repository. This section is intentionally
--     left unresolved pending a product decision (see report).

CREATE OR REPLACE FUNCTION public.fw_admin_funder_pack_content_v1(
  p_release_id uuid
  ) RETURNS jsonb
  LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
  DECLARE
    v_r public.funder_deal_releases;
      v_match record;
        v_match_resolved boolean := false;
          v_buyer_org record;
            v_seller_org record;
              v_wad record;
                v_wad_found boolean := false;
                  v_buyer_summary jsonb;
                    v_seller_summary jsonb;
                      v_verification jsonb;
                        v_idv_kyb jsonb;
                          v_wad_status jsonb;
                            v_evidence_register jsonb;
                              v_missing_evidence jsonb;
                                v_risk_exceptions jsonb;
                                  v_result jsonb;
                                  BEGIN
                                    IF NOT public.p5b3_is_platform_admin() THEN
                                        RAISE EXCEPTION 'fw.forbidden: platform_admin required';
                                          END IF;

                                            SELECT * INTO v_r FROM public.funder_deal_releases WHERE id = p_release_id;
                                              IF NOT FOUND THEN
                                                  RAISE EXCEPTION 'fw.not_found: release not found';
                                                    END IF;

                                                      -- Attempt to resolve deal_reference as a matches.id UUID. Never fabricate:
                                                        -- if it does not parse as a UUID or does not match a row, resolution
                                                          -- fails and every match-scoped section stays explicitly unavailable.
                                                            BEGIN
                                                                IF v_r.deal_reference ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$' THEN
                                                                      SELECT * INTO v_match FROM public.matches WHERE id = v_r.deal_reference::uuid;
                                                                            IF FOUND THEN
                                                                                    v_match_resolved := true;
                                                                                          END IF;
                                                                                              END IF;
                                                                                                EXCEPTION WHEN OTHERS THEN
                                                                                                    v_match_resolved := false;
                                                                                                      END;
                                                                                                      
                                                                                                        IF v_match_resolved THEN
                                                                                                            SELECT id, legal_name, trading_name, registration_number, jurisdictions
                                                                                                                  INTO v_buyer_org FROM public.organizations WHERE id = v_match.buyer_org_id;
                                                                                                                      SELECT id, legal_name, trading_name, registration_number, jurisdictions
                                                                                                                            INTO v_seller_org FROM public.organizations WHERE id = v_match.seller_org_id;
                                                                                                                            
                                                                                                                                v_buyer_summary := jsonb_build_object(
                                                                                                                                      'available', true,
                                                                                                                                            'role', 'buyer',
                                                                                                                                                  'legal_name', coalesce(v_buyer_org.legal_name, v_buyer_org.trading_name),
                                                                                                                                                        'registration_number', v_buyer_org.registration_number,
                                                                                                                                                              'jurisdictions', to_jsonb(coalesce(v_buyer_org.jurisdictions, ARRAY[]::text[]))
                                                                                                                                                                  );
                                                                                                                                                                      v_seller_summary := jsonb_build_object(
                                                                                                                                                                            'available', true,
                                                                                                                                                                                  'role', 'seller',
                                                                                                                                                                                        'legal_name', coalesce(v_seller_org.legal_name, v_seller_org.trading_name),
                                                                                                                                                                                              'registration_number', v_seller_org.registration_number,
                                                                                                                                                                                                    'jurisdictions', to_jsonb(coalesce(v_seller_org.jurisdictions, ARRAY[]::text[]))
                                                                                                                                                                                                        );
                                                                                                                                                                                                        
                                                                                                                                                                                                            -- Verification summary -- company-level screening categories only.
                                                                                                                                                                                                                SELECT jsonb_agg(jsonb_build_object(
                                                                                                                                                                                                                        'party', CASE s.party_role WHEN 'buyer_company' THEN 'buyer' ELSE 'seller' END,
                                                                                                                                                                                                                                'category', cs.category,
                                                                                                                                                                                                                                        'state', cs.state,
                                                                                                                                                                                                                                                'decided_at', cs.decided_at,
                                                                                                                                                                                                                                                        'expires_at', cs.expires_at
                                                                                                                                                                                                                                                              ))
                                                                                                                                                                                                                                                                    INTO v_verification
                                                                                                                                                                                                                                                                          FROM public.p5scr_subjects s
                                                                                                                                                                                                                                                                                JOIN public.p5scr_check_state cs ON cs.subject_id = s.id
                                                                                                                                                                                                                                                                                      WHERE s.party_role IN ('buyer_company','seller_company')
                                                                                                                                                                                                                                                                                              AND s.organisation_id IN (v_match.buyer_org_id, v_match.seller_org_id)
                                                                                                                                                                                                                                                                                                      AND cs.category IN ('company_aml_sanctions','pep','watchlist_name','adverse_media_admin_triggered');
                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                          -- IDV/KYB summary -- identity-verification category, kept separate from
                                                                                                                                                                                                                                                                                                              -- the broader verification summary per the brief's explicit split.
                                                                                                                                                                                                                                                                                                                  SELECT jsonb_agg(jsonb_build_object(
                                                                                                                                                                                                                                                                                                                          'party', CASE s.party_role WHEN 'buyer_company' THEN 'buyer' ELSE 'seller' END,
                                                                                                                                                                                                                                                                                                                                  'category', cs.category,
                                                                                                                                                                                                                                                                                                                                          'state', cs.state,
                                                                                                                                                                                                                                                                                                                                                  'decided_at', cs.decided_at
                                                                                                                                                                                                                                                                                                                                                        ))
                                                                                                                                                                                                                                                                                                                                                              INTO v_idv_kyb
                                                                                                                                                                                                                                                                                                                                                                    FROM public.p5scr_subjects s
                                                                                                                                                                                                                                                                                                                                                                          JOIN public.p5scr_check_state cs ON cs.subject_id = s.id
                                                                                                                                                                                                                                                                                                                                                                                WHERE s.party_role IN ('buyer_company','seller_company')
                                                                                                                                                                                                                                                                                                                                                                                        AND s.organisation_id IN (v_match.buyer_org_id, v_match.seller_org_id)
                                                                                                                                                                                                                                                                                                                                                                                                AND cs.category = 'idv_person';
                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                    -- WaD status -- same relationship already used by deal-certificate.
                                                                                                                                                                                                                                                                                                                                                                                                        SELECT id, status, sealed_at, seal_hash, created_at
                                                                                                                                                                                                                                                                                                                                                                                                              INTO v_wad
                                                                                                                                                                                                                                                                                                                                                                                                                    FROM public.wads
                                                                                                                                                                                                                                                                                                                                                                                                                          WHERE poi_id = v_match.id
                                                                                                                                                                                                                                                                                                                                                                                                                                ORDER BY created_at DESC
                                                                                                                                                                                                                                                                                                                                                                                                                                      LIMIT 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                          v_wad_found := FOUND;
                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                              IF v_wad_found THEN
                                                                                                                                                                                                                                                                                                                                                                                                                                                    v_wad_status := jsonb_build_object(
                                                                                                                                                                                                                                                                                                                                                                                                                                                            'available', true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'exists', true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'status', v_wad.status,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'sealed', (v_wad.status = 'sealed'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'reference', v_wad.id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'sealed_at', v_wad.sealed_at,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'has_seal_hash', (v_wad.seal_hash IS NOT NULL),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'recorded_at', v_wad.created_at
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ELSE
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    v_wad_status := jsonb_build_object(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'available', true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'exists', false,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'status', 'no_wad_recorded'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      END IF;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          -- Evidence register -- safe metadata only, no raw file access.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              SELECT jsonb_agg(jsonb_build_object(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      'category', d.doc_type,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              'label', d.filename,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      'status', d.status,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              'has_hash', (d.sha256_hash IS NOT NULL),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      'recorded_at', d.created_at
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ) ORDER BY d.created_at)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  INTO v_evidence_register
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        FROM public.match_documents d
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              WHERE d.match_id = v_match.id;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  v_missing_evidence := jsonb_build_object(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        'available', false,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              'status', 'not_configured',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'reason', 'No canonical required-evidence checklist exists at the match level in this build. Only received evidence (see evidence register) can be shown honestly.'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            -- Risk / exception summary -- existing safe RPC, organisation-scoped
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                -- (no deal-scoped exception source exists in the platform today).
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    BEGIN
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          SELECT jsonb_agg(jsonb_build_object(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'exception_type', e.exception_type,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              'severity', e.priority,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        'status', e.status,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  'external_safe_summary', e.external_safe_summary,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'created_at', e.created_at,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      'resolved_at', e.resolved_at
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      INTO v_risk_exceptions
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              FROM public.p5b6_list_exceptions_safe(500, 0, NULL, NULL, NULL) e
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      WHERE e.org_id IN (v_match.buyer_org_id, v_match.seller_org_id);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          EXCEPTION WHEN OTHERS THEN
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                v_risk_exceptions := NULL;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    END;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ELSE
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          v_buyer_summary := jsonb_build_object('available', false, 'status', 'unresolved', 'reason', 'No linked record was available at the time of generation.');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              v_seller_summary := jsonb_build_object('available', false, 'status', 'unresolved', 'reason', 'No linked record was available at the time of generation.');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  v_verification := NULL;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      v_idv_kyb := NULL;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          v_wad_status := jsonb_build_object('available', false, 'status', 'unresolved', 'reason', 'No linked record was available at the time of generation.');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              v_evidence_register := NULL;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  v_missing_evidence := jsonb_build_object('available', false, 'status', 'unresolved', 'reason', 'No linked record was available at the time of generation.');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      v_risk_exceptions := NULL;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        END IF;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          v_result := jsonb_build_object(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              'deal_reference_resolved', v_match_resolved,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  'buyer_summary', v_buyer_summary,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      'seller_summary', v_seller_summary,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          'verification_summary', coalesce(v_verification, '[]'::jsonb),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              'idv_kyb_summary', coalesce(v_idv_kyb, '[]'::jsonb),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  'wad_status', v_wad_status,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      'bank_confidence', jsonb_build_object(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'available', false,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  'status', 'not_applicable',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        'reason', 'No authoritative bank-confidence record exists anywhere in this platform build.'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'evidence_register', coalesce(v_evidence_register, '[]'::jsonb),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'missing_evidence', v_missing_evidence,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        'risk_exception_summary', coalesce(v_risk_exceptions, '[]'::jsonb),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'risk_exception_scope', 'organisation',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'finality_snapshot', jsonb_build_object(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      'available', false,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'status', 'not_configured',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  'reason', 'No reliable join exists from this release''s deal reference to a P-5 Batch 4 finality record in this build. A product decision is required (either an explicit case_id link column on funder_deal_releases, or a documented deal_reference/case_reference equality convention) before this section can be safely connected.'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          RETURN v_result;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          END; $$;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          REVOKE EXECUTE ON FUNCTION public.fw_admin_funder_pack_content_v1(uuid) FROM PUBLIC, anon;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          GRANT EXECUTE ON FUNCTION public.fw_admin_funder_pack_content_v1(uuid) TO authenticated, service_role;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
