-- Batch 4 — Funder Evidence Workspace: sealed pack pipeline RPCs + storage policies
-- Additive only. Does not modify existing Batch 1/2/3 RPC signatures.

-- ─── Storage policies for funder-evidence-packs (private bucket) ──────────
-- Only platform admins may write objects; funder users may read their own
-- org's objects via signed URLs generated by the download RPC (service role
-- reads pass regardless). We still add a defence-in-depth SELECT policy so
-- a leaked authenticated JWT cannot enumerate other funders' paths.

CREATE POLICY "fw_pack_storage_admin_all"
  ON storage.objects FOR ALL TO authenticated
  USING (bucket_id = 'funder-evidence-packs' AND public.p5b3_is_platform_admin())
  WITH CHECK (bucket_id = 'funder-evidence-packs' AND public.p5b3_is_platform_admin());

CREATE POLICY "fw_pack_storage_funder_select"
  ON storage.objects FOR SELECT TO authenticated
  USING (
    bucket_id = 'funder-evidence-packs'
    AND EXISTS (
      SELECT 1 FROM public.funder_pack_versions pv
      JOIN public.funder_deal_releases r ON r.id = pv.release_id
      WHERE pv.storage_path = storage.objects.name
        AND pv.storage_bucket = 'funder-evidence-packs'
        AND r.funder_organisation_id = public.p5b3_current_funder_org()
        AND (r.can_download_compiled_pack IS TRUE)
    )
  );

-- ─── RPC: admin seals a pack version after PDF is uploaded ────────────────
CREATE OR REPLACE FUNCTION public.fw_admin_seal_pack_v1(
  p_release_id      uuid,
  p_storage_bucket  text,
  p_storage_path    text,
  p_file_sha256     text,
  p_manifest_sha256 text,
  p_watermark_template text
) RETURNS uuid
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_r      public.funder_deal_releases;
  v_next   integer;
  v_id     uuid;
  v_now    timestamptz := now();
BEGIN
  IF NOT public.p5b3_is_platform_admin() THEN
    RAISE EXCEPTION 'fw.forbidden: platform_admin required';
  END IF;

  IF coalesce(trim(p_storage_bucket),'') = '' OR coalesce(trim(p_storage_path),'') = '' THEN
    RAISE EXCEPTION 'fw.validation: storage bucket/path required';
  END IF;
  IF p_file_sha256 IS NULL OR length(p_file_sha256) <> 64 THEN
    RAISE EXCEPTION 'fw.validation: file_sha256 must be a 64-char hex string';
  END IF;

  SELECT * INTO v_r FROM public.funder_deal_releases WHERE id = p_release_id FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'fw.not_found: release not found';
  END IF;
  IF v_r.release_status <> 'active' THEN
    RAISE EXCEPTION 'fw.state: release is % — only active releases may be sealed', v_r.release_status;
  END IF;
  IF v_r.expires_at IS NOT NULL AND v_r.expires_at <= v_now THEN
    RAISE EXCEPTION 'fw.state: release has expired';
  END IF;

  -- Consent gate: both parties granted/not_required OR an override_reason was captured on the release.
  IF NOT (
    v_r.buyer_consent_status IN ('granted','not_required')
    AND v_r.seller_consent_status IN ('granted','not_required')
  ) THEN
    IF coalesce(trim(v_r.admin_override_reason), '') = '' THEN
      RAISE EXCEPTION 'fw.consent: consent missing and no admin override recorded';
    END IF;
  END IF;

  SELECT coalesce(max(version), 0) + 1
    INTO v_next
    FROM public.funder_pack_versions
   WHERE release_id = p_release_id;

  INSERT INTO public.funder_pack_versions(
    release_id, version, status,
    storage_bucket, storage_path,
    file_sha256, manifest_sha256, watermark_template,
    generated_by, generated_at, sealed_at
  ) VALUES (
    p_release_id, v_next, 'sealed',
    p_storage_bucket, p_storage_path,
    p_file_sha256, p_manifest_sha256, p_watermark_template,
    auth.uid(), v_now, v_now
  ) RETURNING id INTO v_id;

  PERFORM public.fw_audit(
    'funder_pack.sealed', v_r.funder_organisation_id, 'funder_pack_version', v_id,
    NULL,
    jsonb_build_object('version', v_next, 'file_sha256', p_file_sha256, 'bucket', p_storage_bucket, 'path', p_storage_path),
    NULL
  );
  PERFORM public.fw_record_usage(
    v_r.funder_organisation_id, v_r.deal_reference, p_release_id, v_id,
    'pack_generated',
    jsonb_build_object('version', v_next, 'file_sha256', p_file_sha256)
  );

  RETURN v_id;
END; $$;

REVOKE EXECUTE ON FUNCTION public.fw_admin_seal_pack_v1(uuid, text, text, text, text, text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.fw_admin_seal_pack_v1(uuid, text, text, text, text, text) TO authenticated, service_role;

-- ─── RPC: funder authorises a download and records the event ──────────────
CREATE OR REPLACE FUNCTION public.fw_funder_authorize_pack_download_v1(
  p_pack_version_id uuid
) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_pv     public.funder_pack_versions;
  v_r      public.funder_deal_releases;
  v_org    uuid;
  v_now    timestamptz := now();
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'fw.forbidden: authentication required';
  END IF;

  v_org := public.p5b3_current_funder_org();
  IF v_org IS NULL THEN
    RAISE EXCEPTION 'fw.forbidden: not a funder user';
  END IF;

  SELECT * INTO v_pv FROM public.funder_pack_versions WHERE id = p_pack_version_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'fw.not_found: pack version not available';
  END IF;

  SELECT * INTO v_r FROM public.funder_deal_releases WHERE id = v_pv.release_id;
  IF NOT FOUND OR v_r.funder_organisation_id <> v_org THEN
    -- Opaque: do not distinguish existence from cross-org access.
    RAISE EXCEPTION 'fw.not_found: pack version not available';
  END IF;

  IF v_r.release_status <> 'active' THEN
    RAISE EXCEPTION 'fw.state: release is not active';
  END IF;
  IF v_r.expires_at IS NOT NULL AND v_r.expires_at <= v_now THEN
    RAISE EXCEPTION 'fw.state: release has expired';
  END IF;
  IF NOT v_r.can_download_compiled_pack THEN
    RAISE EXCEPTION 'fw.forbidden: compiled pack download is not enabled for this release';
  END IF;
  IF v_pv.status NOT IN ('generated','sealed') OR v_pv.storage_path IS NULL OR v_pv.storage_bucket IS NULL THEN
    RAISE EXCEPTION 'fw.state: pack version is not available for download';
  END IF;

  PERFORM public.fw_audit(
    'funder_pack.download_authorized', v_r.funder_organisation_id,
    'funder_pack_version', v_pv.id,
    NULL,
    jsonb_build_object('version', v_pv.version, 'release_id', v_r.id),
    NULL
  );
  PERFORM public.fw_record_usage(
    v_r.funder_organisation_id, v_r.deal_reference, v_r.id, v_pv.id,
    'pack_downloaded',
    jsonb_build_object('version', v_pv.version, 'file_sha256', v_pv.file_sha256)
  );

  RETURN jsonb_build_object(
    'pack_version_id', v_pv.id,
    'release_id', v_r.id,
    'storage_bucket', v_pv.storage_bucket,
    'storage_path', v_pv.storage_path,
    'file_sha256', v_pv.file_sha256,
    'version', v_pv.version
  );
END; $$;

REVOKE EXECUTE ON FUNCTION public.fw_funder_authorize_pack_download_v1(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.fw_funder_authorize_pack_download_v1(uuid) TO authenticated, service_role;

-- ─── RPC: admin release + pack context, used by the generation edge fn ─────
CREATE OR REPLACE FUNCTION public.fw_admin_pack_generation_context_v1(
  p_release_id uuid
) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_r    public.funder_deal_releases;
  v_org  public.p5_batch3_funder_organisations;
  v_next integer;
BEGIN
  IF NOT public.p5b3_is_platform_admin() THEN
    RAISE EXCEPTION 'fw.forbidden: platform_admin required';
  END IF;

  SELECT * INTO v_r FROM public.funder_deal_releases WHERE id = p_release_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'fw.not_found: release not found';
  END IF;
  IF v_r.release_status <> 'active' THEN
    RAISE EXCEPTION 'fw.state: release is % — only active releases may be generated', v_r.release_status;
  END IF;
  IF v_r.expires_at IS NOT NULL AND v_r.expires_at <= now() THEN
    RAISE EXCEPTION 'fw.state: release has expired';
  END IF;
  IF NOT (
    v_r.buyer_consent_status IN ('granted','not_required')
    AND v_r.seller_consent_status IN ('granted','not_required')
  ) THEN
    IF coalesce(trim(v_r.admin_override_reason), '') = '' THEN
      RAISE EXCEPTION 'fw.consent: consent missing and no admin override recorded';
    END IF;
  END IF;

  SELECT * INTO v_org FROM public.p5_batch3_funder_organisations WHERE id = v_r.funder_organisation_id;

  SELECT coalesce(max(version), 0) + 1
    INTO v_next
    FROM public.funder_pack_versions
   WHERE release_id = p_release_id;

  RETURN jsonb_build_object(
    'release', to_jsonb(v_r),
    'organisation', to_jsonb(v_org),
    'next_version', v_next
  );
END; $$;

REVOKE EXECUTE ON FUNCTION public.fw_admin_pack_generation_context_v1(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.fw_admin_pack_generation_context_v1(uuid) TO authenticated, service_role;