
ALTER TABLE public.pois DROP CONSTRAINT pois_state_check;
ALTER TABLE public.pois ADD CONSTRAINT pois_state_check CHECK (
  state IN ('DRAFT', 'PENDING_APPROVAL', 'ELIGIBLE', 'COMPLETION_REQUESTED', 'COMPLETED', 'EXPIRED', 'ANNULLED', 'REJECTED')
);
